sudo: required
servises:
  - docker

  before_install:
    - docker build -t mikhaildedeiko/react-test -f ./client/Dockerfile.dev ./client
  
  script:
    - docker run -e CI=true mikhaildedeiko/react-test npm test

  after_success:
    - docker build -t mikhaildedeiko/multi-client ./client
    - docker build -t mikhaildedeiko/multi-nginx ./nginx
    - docker build -t mikhaildedeiko/multi-server ./server
    - docker build -t mikhaildedeiko/multi-worker ./worker

    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push mikhaildedeiko/multi-client
    - docker push mikhaildedeiko/multi-nginx
    - docker push mikhaildedeiko/multi-server
    - docker push mikhaildedeiko/muliti-worker
    